name: Continual Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/**
      - bugfix/**
      - dependabot/**

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-versions }}, Laravel ${{ matrix.laravel-versions }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2', '8.3']
        laravel-versions: ['9.*', '10.*', '11.*', '12.*']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-laravel-${{ matrix.laravel-versions }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}-laravel-${{ matrix.laravel-versions }}
            ${{ runner.os }}-php-${{ matrix.php-versions }}-laravel-
            ${{ runner.os }}-php-${{ matrix.php-versions }}-

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction --no-suggest
          composer update "laravel/support:${{ matrix.laravel-versions }}" --with-all-dependencies --prefer-dist --no-progress --no-interaction --no-suggest
          composer install --prefer-dist --no-progress --no-interaction --no-suggest --ignore-platform-reqs

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
